apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd-central
  namespace: platform-argocd
spec:
  aggregatedClusterRoles: true
  defaultClusterScopedRoleDisabled: false
  applicationSet:
    enabled: false
  server:
    host: argocd.k8s.<CUSTOMER_LAB_DOMAIN>
    grpc:
      host: argocd-grpc.k8s.<CUSTOMER_LAB_DOMAIN>
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: selfsigned
          cert-manager.io/issue-temporary-certificate: "false"
          ingress.citrix.com/insecure-termination: redirect
          ingress.citrix.com/ssl-passthrough: "true"
        ingressClassName: vpxingress
        path: "/"
        tls:
        - hosts:
          - argocd-grpc.k8s.<CUSTOMER_LAB_DOMAIN>
          secretName: argocd-grpc-tls
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
        cert-manager.io/issue-temporary-certificate: "false"
        ingress.citrix.com/insecure-termination: redirect
        ingress.citrix.com/ssl-passthrough: "true"
      ingressClassName: vpxingress
      path: "/"
      tls:
      - hosts:
        - argocd.k8s.<CUSTOMER_LAB_DOMAIN>
        secretName: argocd-tls
    insecure: false
    replicas: 1
