apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-platform-repo
  namespace: platform-argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eso-store-platform
  target:
    name: platform-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        insecure: "false"
        type: "git"
        project: "platform"
        name: "<GITHUB_REPO>"
        url: "git@github.com:<GITHUB_ORG>/<GITHUB_REPO>.git"
        sshPrivateKey: "{{ .sshKey | toString }}"

  data:
  - secretKey: sshKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: argocd-sshKey-gitops
      metadataPolicy: None