apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-nslogin
  namespace: platform-netscaler
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eso-store-platform
  target:
    name: nslogin
    template:
      metadata:
      data:
        username: "nsic"
        password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: netscaler-login
      metadataPolicy: None