#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: #@ data.values.name + "-externaldns-internal"
  namespace: platform-argocd
  labels:
    app: "externaldns-internal"
spec:
  destination:
    name: #@ data.values.name
    namespace: platform-externaldns
  project: platform
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: #@ "deployments/" + data.values.name + "/externaldns-internal"
    repoURL: ssh://git@github.com:<GITHUB_ORG>/<GITHUB_REPO>.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
