#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: #@ data.values.name + "-adcs-issuer"
  namespace: platform-argocd
  labels:
    app: "adcs-issuer"
spec:
  destination:
    name: #@ data.values.name
    namespace: platform-adcs-issuer
  project: platform
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: #@ "deployments/" + data.values.name + "/adcs-issuer"
    repoURL: ssh://git@github.com:<GITHUB_ORG>/<GITHUB_REPO>.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
