apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-prod01-all-apps
  namespace: platform-argocd
  labels:
    app: cluster-all-apps
spec:
  destination:
    name: platform-prod01
    namespace: platform-argocd
  project: platform
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: deployments/platform-prod01/argocd-apps
    repoURL: ssh://git@github.com:<GITHUB_ORG>/<GITHUB_REPO>.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
