---
# External Secret using External Secrets Operator
# This pulls secrets from Azure Key Vault and creates the ArgoCD OIDC Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-argocd-oidc
  namespace: platform-argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-store-platform
    kind: SecretStore
  target:
    name: argocd-oidc
    creationPolicy: Owner
  data:
    # Pull OIDC client secret from Azure Key Vault
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: argocd-oidc-clientSecret
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: argocd-oidc-clientId