---
# External Secret using External Secrets Operator
# This pulls secrets from Azure Key Vault and creates the ArgoCD OIDC Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-argocd-oidc
  namespace: platform-argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-store-platform
    kind: SecretStore
  target:
    name: argocd-oidc
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    # Pull OIDC client secret from Azure Key Vault
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-oidc-clientSecret
        metadataPolicy: None
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-oidc-clientId
        metadataPolicy: None