apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-manager
    app.kubernetes.io/part-of: argocd
  name: argocd-manager
  namespace: kube-system