apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-externaldns-kerberos
  namespace: platform-externaldns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-store-platform
  target:
    name: externaldns-kerberos
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: externaldns-kerberos-username
  - secretKey: password
    remoteRef:
      key: externaldns-kerberos-password
