apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-adcs-credentials
  namespace: platform-adcs-issuer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-store-platform
  target:
    name: adcs-credentials
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: adcs-credentials-username
      metadataPolicy: None
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: adcs-credentials-password
      metadataPolicy: None
