#@ load("@ytt:data", "data")
---
apiVersion: adcs.certmanager.csf.nokia.com/v1
kind: ClusterAdcsIssuer
metadata:
  name: <CUSTOMER_SHORT>-adcs-issuer
spec:
  url: #@ data.values.adcs.url
  credentialsRef:
    name: adcs-credentials
  statusCheckInterval: #@ data.values.adcs.statusCheckInterval
  retryInterval: #@ data.values.adcs.retryInterval
  templateName: #@ data.values.adcs.templateName
